version: "3.9"
services:
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=db
    ports:
      - 5432:5432

